# Generated by Django 4.2.9 on 2024-05-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinregister',
            name='activity',
            field=models.TextField(blank=True, verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='checkinregister',
            name='date_register',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='checkinregister',
            name='type_register',
            field=models.CharField(choices=[('Check-in', 'Check-in'), ('Lunch', 'Lunch'), ('Check-out', 'Check-out')], max_length=10),
        ),
    ]
