# Generated by Django 4.2.9 on 2024-05-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_checkin', '0002_checkinregister_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinregister',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
