# Generated by Django 4.2.9 on 2024-05-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_checkin', '0003_checkinregister_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinregister',
            name='hours_worked',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
