# Generated by Django 4.2.9 on 2024-05-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_checkin', '0005_remove_checkinregister_type_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinregister',
            name='type_register',
            field=models.CharField(choices=[('Check-in', 'Check-in'), ('Check-out', 'Check-out')], default='Check-in', max_length=10),
        ),
    ]
