# Generated by Django 4.2.9 on 2024-05-12 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_base', '0007_task'),
        ('project_checkin', '0007_attendance_employee_delete_checkinregister_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_register', models.DateTimeField()),
                ('activity', models.TextField(blank=True, verbose_name='Activity')),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('hours_worked', models.FloatField(blank=True, null=True)),
                ('type_register', models.CharField(choices=[('Check-in', 'Check-in'), ('Check-out', 'Check-out')], default='Check-in', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_base.cadastroprojeto')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
