# Generated by Django 4.2.9 on 2024-02-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150, verbose_name='Project Name')),
                ('project_description', models.TextField(blank=True, verbose_name='Project Description')),
                ('client_name', models.CharField(max_length=150, verbose_name='Client Name')),
                ('client_contact', models.CharField(max_length=150, verbose_name='Phone Number')),
                ('project_adress', models.TextField(blank=True, verbose_name='Project Adress')),
                ('estimated_budget', models.IntegerField(blank=True, null=True, verbose_name='Estimated Budget')),
                ('total_amount_spend', models.IntegerField(blank=True, null=True, verbose_name='Total Amount Spent')),
                ('estimated_project_duration', models.IntegerField(blank=True, null=True, verbose_name='Estimated Project Duration')),
            ],
        ),
    ]
