# Generated by Django 4.2.9 on 2024-05-06 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_base', '0002_registrodepresenca'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo_registro', models.CharField(choices=[('Check-in', 'Check-in'), ('Check-out', 'Check-out')], max_length=10)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_base.cadastroprojeto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RegistroDePresenca',
        ),
    ]
