# Generated by Django 4.2.9 on 2024-05-07 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_base', '0003_registroponto_delete_registrodepresenca'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroPonto',
        ),
    ]
