# Generated by Django 4.2.9 on 2024-05-07 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_client', '0001_initial'),
        ('project_base', '0004_delete_registroponto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastroprojeto',
            name='client_contact',
        ),
        migrations.AlterField(
            model_name='cadastroprojeto',
            name='client_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_client.client'),
        ),
    ]
