# Generated by Django 4.2.9 on 2024-05-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_base', '0005_remove_cadastroprojeto_client_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroprojeto',
            name='project_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Project Name'),
        ),
    ]
