# Generated by Django 4.2.9 on 2024-05-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_base', '0006_alter_cadastroprojeto_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('estimated_time', models.DurationField()),
            ],
        ),
    ]
