# Generated by Django 4.2.9 on 2024-05-13 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_base', '0007_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='estimated_time',
            new_name='time_estimate',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='text',
            new_name='title',
        ),
    ]
