# Generated by Django 4.2.9 on 2024-05-21 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_base', '0008_rename_estimated_time_task_time_estimate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='time_estimate',
            new_name='estimated_time',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='text',
        ),
    ]
